# openapi2-functions.yaml
swagger: '2.0'
info:
  title: resume-api 
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /update_visitor_count:
    post:
      summary: Increment visitor count
      operationId: update_visitor_count
      x-google-backend:
        address: https://europe-west9-resume-404711.cloudfunctions.net/update_visitor_count
      responses:
        '200':
          description: A successful response
          schema:
            type: string
